source 'http://rubygems.org'

gem 'rails', '~> 4.2.1'
gem 'pg', '~> 0.18.1'
gem 'rake', '~> 10.4.2'
gem 'uglifier', '>= 1.3.0'
gem 'unicorn'

gem 'sass-rails'
gem 'autoprefixer-rails'
gem 'font-awesome-sass', '~> 4.2.0'

gem 'foreman'
gem 'capistrano', '2.14.2'
gem 'nokogiri', '~> 1.6.6.2'
gem 'httparty', '~> 0.13.3'
gem 'treyconnell-ruby-aaws', '0.8.1'
gem 'em-websocket', :git => "https://github.com/errordeveloper/em-websocket"
gem 'addressable', '2.2.6'
gem 'eventmachine', '1.0.4'
gem 'http_parser.rb', '0.6.0'
gem "iconv", '1.0.4'
gem 'slack-ruby-client', '0.6.0'
gem 'json', '1.8.2'
gem 'minitest', '5.6.0'

gem "figaro"
gem 'whenever', '~> 0.9.4', :require => false
gem 'rspotify', '~> 1.18.0'

gem 'delayed_job', '~> 4.0.6'
gem 'delayed_job_active_record', '~> 4.0.3'

group :development do
  gem 'thin'
  gem 'capistrano-kyan', :git => "https://github.com/kyan/capistrano-kyan.git", :require => false
  gem 'capistrano-unicorn', :require => false
end

group :assets do
  gem 'execjs', '1.4.0'
  gem 'therubyracer', '0.12.1', :platform => :ruby
end

group :test, :development do
  gem 'pry-byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'spring-commands-rspec', group: :development
  gem 'rspec-rails', '~> 3.0'
end
