# encoding: utf-8

# require 'thread'
# require(File.join(File.dirname(__FILE__), 'config', 'boot'))

# require 'rake'
# require 'rake/testtask'
# require 'rdoc/task'

# require 'tasks/rails'

# begin
#   gem 'delayed_job', '~>2.0.4'
#   require 'delayed/tasks'
# rescue LoadError
#   STDERR.puts "Run `rake gems:install` to install delayed_job"
# end


require File.expand_path('../config/application', __FILE__)

Jukebox::Application.load_tasks